version: "3"

services:
    server:
        build: server/
        command: yarn dev
        ports:
            - 4000:4000
        volumes:
            - ./server/src:/app/server/src
    client:
        build: client/
        command: yarn start
        ports:
            - 3000:3000
        volumes:
            - ./client/src:/app/client/src
        depends_on:
            - server