version: "3"

services:
    server:
        build:
            context: ./server
            dockerfile: Dockerfile.dev
        command: yarn dev
        ports:
            - 4000:4000
        volumes:
            - ./server:/app/server:ro
        container_name: 
            backend
        image:
            amanc92/link-up:server
    client:
        build:
            context: ./client
            dockerfile: Dockerfile.dev
        command: yarn start
        ports:
            - 3000:3000
        volumes:
            - ./client/src:/app/client/src:ro
        container_name: 
            frontend
        image:
            amanc92/link-up:client
        depends_on:
            - server
