version: "3"

services:
    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile.dev
        ports:
            - 80:80
        restart: always
        container_name:
            routing
        image:
            amanc92/link-up:nginx
        container_name:
            nginx
        image:
            amanc92/link-up:nginx
        depends_on:
            - server
            - client
    server:
        build:
            context: ./server
            dockerfile: Dockerfile.dev
        command: yarn dev
        volumes:
            - ./server:/app/server:ro
<<<<<<< HEAD
        container_name: 
            backend
=======
>>>>>>> a44c299 (Changed development volume to point to all contents in server/ folder as server.js was not being refreshed.)
    client:
        build:
            context: ./client
            dockerfile: Dockerfile.dev
        command: yarn start
        volumes:
            - ./client/src:/app/client/src:ro
        container_name: 
            client
        depends_on:
            - server
