version: "3"

services:
    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - 80:80
        restart: always
        container_name: nginx
        image: amanc92/dev-link-up:nginx
        depends_on:
            - server
            - client
    server:
        build:
            context: ./server
            dockerfile: Dockerfile.dev
        command: yarn dev
        volumes:
            - ./server:/app/server:ro
        restart: on-failure
        container_name: server
        image: amanc92/dev-link-up:server
    client:
        build:
            context: ./client
            dockerfile: Dockerfile.dev
        command: yarn start
        volumes:
            - ./client/src:/app/client/src:ro
        restart: on-failure
        container_name: client
        image: amanc92/dev-link-up:client
        depends_on:
            - server
